import { Spread } from "@/types/tarot"

export const SPREADS: Spread[] = [
  {
    id: "single-card",
    name: "Single Card",
    description: "Quick guidance for a specific question or daily insight",
    cardCount: 1,
    layout: "linear",
    positions: [
      {
        id: "card-1",
        name: "Your Card",
        description: "The answer to your question or guidance for today",
        x: 50,
        y: 50,
      },
    ],
  },
  {
    id: "three-card",
    name: "Three Card Spread",
    description: "Past, Present, Future - Classic spread for understanding situations",
    cardCount: 3,
    layout: "linear",
    positions: [
      {
        id: "past",
        name: "Past",
        description: "What has led to your current situation",
        x: 25,
        y: 50,
      },
      {
        id: "present",
        name: "Present",
        description: "Your current circumstances and influences",
        x: 50,
        y: 50,
      },
      {
        id: "future",
        name: "Future",
        description: "Potential outcome if current path continues",
        x: 75,
        y: 50,
      },
    ],
  },
  {
    id: "celtic-cross",
    name: "Celtic Cross",
    description: "Comprehensive 10-card spread for deep insight into complex situations",
    cardCount: 10,
    layout: "cross",
    positions: [
      {
        id: "present",
        name: "Present",
        description: "The heart of the situation",
        x: 50,
        y: 50,
      },
      {
        id: "challenge",
        name: "Challenge",
        description: "Obstacles or opposing forces",
        x: 50,
        y: 35,
      },
      {
        id: "past",
        name: "Past",
        description: "Recent events influencing the situation",
        x: 35,
        y: 50,
      },
      {
        id: "future",
        name: "Future",
        description: "Near future influences",
        x: 65,
        y: 50,
      },
      {
        id: "above",
        name: "Above",
        description: "Best possible outcome or conscious goals",
        x: 50,
        y: 20,
      },
      {
        id: "below",
        name: "Below",
        description: "Subconscious influences or foundation",
        x: 50,
        y: 80,
      },
      {
        id: "advice",
        name: "Advice",
        description: "Recommended course of action",
        x: 20,
        y: 35,
      },
      {
        id: "external",
        name: "External",
        description: "External influences and environment",
        x: 80,
        y: 35,
      },
      {
        id: "hopes-fears",
        name: "Hopes & Fears",
        description: "Your hopes and fears about the situation",
        x: 20,
        y: 65,
      },
      {
        id: "outcome",
        name: "Outcome",
        description: "Likely outcome if current path continues",
        x: 80,
        y: 65,
      },
    ],
  },
  {
    id: "relationship",
    name: "Relationship Spread",
    description: "Understand dynamics between two people",
    cardCount: 5,
    layout: "custom",
    positions: [
      {
        id: "you",
        name: "You",
        description: "Your perspective and feelings",
        x: 25,
        y: 50,
      },
      {
        id: "other",
        name: "Other Person",
        description: "Their perspective and feelings",
        x: 75,
        y: 50,
      },
      {
        id: "connection",
        name: "Connection",
        description: "The bond between you",
        x: 50,
        y: 50,
      },
      {
        id: "strengths",
        name: "Strengths",
        description: "Positive aspects of the relationship",
        x: 50,
        y: 30,
      },
      {
        id: "challenges",
        name: "Challenges",
        description: "Areas needing attention",
        x: 50,
        y: 70,
      },
    ],
  },
  {
    id: "career",
    name: "Career Spread",
    description: "Guidance for career decisions and professional growth",
    cardCount: 5,
    layout: "linear",
    positions: [
      {
        id: "current",
        name: "Current Situation",
        description: "Your present career status",
        x: 10,
        y: 50,
      },
      {
        id: "strengths",
        name: "Strengths",
        description: "Your professional assets",
        x: 30,
        y: 50,
      },
      {
        id: "challenges",
        name: "Challenges",
        description: "Obstacles to overcome",
        x: 50,
        y: 50,
      },
      {
        id: "opportunities",
        name: "Opportunities",
        description: "Potential paths forward",
        x: 70,
        y: 50,
      },
      {
        id: "advice",
        name: "Advice",
        description: "Guidance for career decisions",
        x: 90,
        y: 50,
      },
    ],
  },
  {
    id: "yes-no",
    name: "Yes/No Spread",
    description: "Simple yes or no answer to your question",
    cardCount: 3,
    layout: "linear",
    positions: [
      {
        id: "yes",
        name: "Yes",
        description: "Factors supporting a yes answer",
        x: 25,
        y: 50,
      },
      {
        id: "no",
        name: "No",
        description: "Factors supporting a no answer",
        x: 75,
        y: 50,
      },
      {
        id: "outcome",
        name: "Outcome",
        description: "Most likely answer",
        x: 50,
        y: 50,
      },
    ],
  },
  {
    id: "four-directions",
    name: "Four Directions Spread",
    description: "Holistic view of your situation from all angles",
    cardCount: 4,
    layout: "cross",
    positions: [
      {
        id: "north",
        name: "North (Wisdom)",
        description: "What you need to learn",
        x: 50,
        y: 20,
      },
      {
        id: "east",
        name: "East (New Beginnings)",
        description: "New opportunities approaching",
        x: 80,
        y: 50,
      },
      {
        id: "south",
        name: "South (Passion)",
        description: "What drives you emotionally",
        x: 50,
        y: 80,
      },
      {
        id: "west",
        name: "West (Introspection)",
        description: "What you need to release",
        x: 20,
        y: 50,
      },
    ],
  },
  {
    id: "five-card",
    name: "Five Card Spread",
    description: "Detailed analysis of a specific situation",
    cardCount: 5,
    layout: "linear",
    positions: [
      {
        id: "situation",
        name: "Situation",
        description: "Current circumstances",
        x: 10,
        y: 50,
      },
      {
        id: "action",
        name: "Action",
        description: "What you should do",
        x: 30,
        y: 50,
      },
      {
        id: "outcome",
        name: "Outcome",
        description: "Result of your action",
        x: 50,
        y: 50,
      },
      {
        id: "internal",
        name: "Internal",
        description: "Your inner state",
        x: 70,
        y: 50,
      },
      {
        id: "external",
        name: "External",
        description: "External influences",
        x: 90,
        y: 50,
      },
    ],
  },
  {
    id: "seven-card",
    name: "Seven Card Spread",
    description: "Week ahead forecast or comprehensive situation analysis",
    cardCount: 7,
    layout: "linear",
    positions: [
      {
        id: "day-1",
        name: "Day 1",
        description: "First day or aspect",
        x: 10,
        y: 50,
      },
      {
        id: "day-2",
        name: "Day 2",
        description: "Second day or aspect",
        x: 23,
        y: 50,
      },
      {
        id: "day-3",
        name: "Day 3",
        description: "Third day or aspect",
        x: 36,
        y: 50,
      },
      {
        id: "day-4",
        name: "Day 4",
        description: "Fourth day or aspect",
        x: 50,
        y: 50,
      },
      {
        id: "day-5",
        name: "Day 5",
        description: "Fifth day or aspect",
        x: 63,
        y: 50,
      },
      {
        id: "day-6",
        name: "Day 6",
        description: "Sixth day or aspect",
        x: 76,
        y: 50,
      },
      {
        id: "day-7",
        name: "Day 7",
        description: "Seventh day or aspect",
        x: 90,
        y: 50,
      },
    ],
  },
  {
    id: "star",
    name: "Star Spread",
    description: "Hope and guidance for your path forward",
    cardCount: 7,
    layout: "custom",
    positions: [
      {
        id: "center",
        name: "Center",
        description: "Core issue or question",
        x: 50,
        y: 50,
      },
      {
        id: "top",
        name: "Top",
        description: "Spiritual guidance",
        x: 50,
        y: 20,
      },
      {
        id: "bottom",
        name: "Bottom",
        description: "Practical matters",
        x: 50,
        y: 80,
      },
      {
        id: "left",
        name: "Left",
        description: "Past influences",
        x: 20,
        y: 50,
      },
      {
        id: "right",
        name: "Right",
        description: "Future potential",
        x: 80,
        y: 50,
      },
      {
        id: "top-left",
        name: "Top Left",
        description: "What to embrace",
        x: 25,
        y: 25,
      },
      {
        id: "top-right",
        name: "Top Right",
        description: "What to avoid",
        x: 75,
        y: 25,
      },
    ],
  },
  {
    id: "mandala",
    name: "Mandala Spread",
    description: "Circular spread for holistic self-reflection",
    cardCount: 8,
    layout: "circle",
    positions: [
      {
        id: "self",
        name: "Self",
        description: "Your current state",
        x: 50,
        y: 50,
      },
      {
        id: "desire",
        name: "Desire",
        description: "What you want",
        x: 50,
        y: 20,
      },
      {
        id: "fear",
        name: "Fear",
        description: "What you fear",
        x: 80,
        y: 35,
      },
      {
        id: "strength",
        name: "Strength",
        description: "Your inner power",
        x: 80,
        y: 65,
      },
      {
        id: "weakness",
        name: "Weakness",
        description: "Areas to improve",
        x: 50,
        y: 80,
      },
      {
        id: "lesson",
        name: "Lesson",
        description: "What to learn",
        x: 20,
        y: 65,
      },
      {
        id: "gift",
        name: "Gift",
        description: "Your unique contribution",
        x: 20,
        y: 35,
      },
      {
        id: "path",
        name: "Path",
        description: "Your journey forward",
        x: 50,
        y: 50,
      },
    ],
  },
  {
    id: "horseshoe",
    name: "Horseshoe Spread",
    description: "Traditional spread for general life questions",
    cardCount: 7,
    layout: "custom",
    positions: [
      {
        id: "past",
        name: "Past",
        description: "Recent past influences",
        x: 20,
        y: 50,
      },
      {
        id: "present",
        name: "Present",
        description: "Current situation",
        x: 35,
        y: 50,
      },
      {
        id: "hidden",
        name: "Hidden Influences",
        description: "Factors not immediately visible",
        x: 50,
        y: 50,
      },
      {
        id: "obstacles",
        name: "Obstacles",
        description: "Challenges to overcome",
        x: 65,
        y: 50,
      },
      {
        id: "environment",
        name: "Environment",
        description: "External factors",
        x: 80,
        y: 50,
      },
      {
        id: "hopes",
        name: "Hopes",
        description: "Your aspirations",
        x: 50,
        y: 70,
      },
      {
        id: "outcome",
        name: "Outcome",
        description: "Likely result",
        x: 50,
        y: 85,
      },
    ],
  },
]

export function getSpreadById(id: string): Spread | undefined {
  return SPREADS.find((spread) => spread.id === id)
}

export function getAllSpreads(): Spread[] {
  return SPREADS
}
