import { TarotCard } from '@/types/tarot';

export const tarotCards: TarotCard[] = [
  // Major Arcana (22 cards)
  {
    id: 'major_arcana_fool',
    name: 'The Fool',
    number: 0,
    type: 'major',
    image: '/cards/major/major_arcana_fool.png',
    keywords: ['new beginnings', 'innocence', 'spontaneity', 'faith', 'free spirit'],
    upright: {
      meaning: 'Embrace new adventures with trust and innocence. Take a leap of faith into the unknown.',
      keywords: ['new beginnings', 'innocence', 'spontaneity', 'faith', 'free spirit'],
      description: 'The Fool represents new beginnings, having faith in the future, being inexperienced, not knowing what to expect, having beginner\'s luck, improvisation and believing in the universe.',
    },
    reversed: {
      meaning: 'Recklessness, taking unnecessary risks, naivety, being taken advantage of, inconsideration.',
      keywords: ['recklessness', 'risk', 'naivety', 'foolishness', 'inconsideration'],
      description: 'The Fool reversed suggests recklessness, being taken advantage of, inconsideration, naivety, risk-taking and foolishness.',
    },
  },
  {
    id: 'major_arcana_magician',
    name: 'The Magician',
    number: 1,
    type: 'major',
    image: '/cards/major/major_arcana_magician.png',
    keywords: ['manifestation', 'resourcefulness', 'power', 'skill', 'action'],
    upright: {
      meaning: 'You have all the tools needed to manifest your desires. Take action and create your reality.',
      keywords: ['manifestation', 'resourcefulness', 'power', 'skill', 'action'],
      description: 'The Magician represents manifestation, resourcefulness, power and inspired action. He is the bridge between the world of the spirit and the world of humanity.',
    },
    reversed: {
      meaning: 'Manipulation, poor planning, untapped talents, latent abilities, trickery.',
      keywords: ['manipulation', 'poor planning', 'untapped talents', 'weakness', 'trickery'],
      description: 'The Magician reversed suggests manipulation, poor planning, untapped talents, latent abilities and trickery.',
    },
  },
  {
    id: 'major_arcana_priestess',
    name: 'The High Priestess',
    number: 2,
    type: 'major',
    image: '/cards/major/major_arcana_priestess.png',
    keywords: ['intuition', 'subconscious', 'mystery', 'inner knowledge', 'divine feminine'],
    upright: {
      meaning: 'Trust your intuition and look beneath the surface. The answers lie within.',
      keywords: ['intuition', 'subconscious', 'mystery', 'inner knowledge', 'divine feminine'],
      description: 'The High Priestess represents intuition, mystery, spirituality and the subconscious mind. She sits at the gate of the great mystery.',
    },
    reversed: {
      meaning: 'Secrets, disconnected from intuition, withdrawal, silence, repressed feelings.',
      keywords: ['secrets', 'disconnection', 'withdrawal', 'silence', 'repressed feelings'],
      description: 'The High Priestess reversed suggests secrets, disconnection from intuition, withdrawal, silence and repressed feelings.',
    },
  },
  {
    id: 'major_arcana_empress',
    name: 'The Empress',
    number: 3,
    type: 'major',
    image: '/cards/major/major_arcana_empress.png',
    keywords: ['femininity', 'beauty', 'nature', 'nurturing', 'abundance'],
    upright: {
      meaning: 'Embrace your feminine energy. Connect with nature and nurture yourself and others.',
      keywords: ['femininity', 'beauty', 'nature', 'nurturing', 'abundance'],
      description: 'The Empress represents femininity, beauty, nature, nurturing and abundance. She is the mother of the earth.',
    },
    reversed: {
      meaning: 'Creative block, dependence on others, smothering, emptiness, superficiality.',
      keywords: ['creative block', 'dependence', 'smothering', 'emptiness', 'superficiality'],
      description: 'The Empress reversed suggests creative block, dependence on others, smothering, emptiness and superficiality.',
    },
  },
  {
    id: 'major_arcana_emperor',
    name: 'The Emperor',
    number: 4,
    type: 'major',
    image: '/cards/major/major_arcana_emperor.png',
    keywords: ['authority', 'structure', 'control', 'fatherhood', 'leadership'],
    upright: {
      meaning: 'Take control of your life. Establish structure and authority. Lead with confidence.',
      keywords: ['authority', 'structure', 'control', 'fatherhood', 'leadership'],
      description: 'The Emperor represents authority, structure, control and leadership. He is the father figure who provides stability and protection.',
    },
    reversed: {
      meaning: 'Domination, excessive control, lack of discipline, rigidity, coldness.',
      keywords: ['domination', 'excessive control', 'lack of discipline', 'rigidity', 'coldness'],
      description: 'The Emperor reversed suggests domination, excessive control, lack of discipline, rigidity and coldness.',
    },
  },
  {
    id: 'major_arcana_hierophant',
    name: 'The Hierophant',
    number: 5,
    type: 'major',
    image: '/cards/major/major_arcana_hierophant.png',
    keywords: ['tradition', 'conformity', 'morality', 'ethics', 'religious beliefs'],
    upright: {
      meaning: 'Follow traditional values and seek spiritual guidance. Learn from teachers and mentors.',
      keywords: ['tradition', 'conformity', 'morality', 'ethics', 'religious beliefs'],
      description: 'The Hierophant represents tradition, conformity, morality and ethics. He is the spiritual teacher who guides others on their path.',
    },
    reversed: {
      meaning: 'Rebellion, subversiveness, new approaches, unconventionality, freedom.',
      keywords: ['rebellion', 'subversiveness', 'new approaches', 'unconventionality', 'freedom'],
      description: 'The Hierophant reversed suggests rebellion, subversiveness, new approaches, unconventionality and freedom.',
    },
  },
  {
    id: 'major_arcana_lovers',
    name: 'The Lovers',
    number: 6,
    type: 'major',
    image: '/cards/major/major_arcana_lovers.png',
    keywords: ['love', 'harmony', 'relationships', 'values alignment', 'choices'],
    upright: {
      meaning: 'Embrace love and harmony. Make choices that align with your values and heart.',
      keywords: ['love', 'harmony', 'relationships', 'values alignment', 'choices'],
      description: 'The Lovers represents love, harmony, relationships and choices. It signifies a union of opposites and the importance of making decisions from the heart.',
    },
    reversed: {
      meaning: 'Self-love, disharmony, imbalance, misalignment of values, indulgence.',
      keywords: ['self-love', 'disharmony', 'imbalance', 'misalignment', 'indulgence'],
      description: 'The Lovers reversed suggests self-love, disharmony, imbalance, misalignment of values and indulgence.',
    },
  },
  {
    id: 'major_arcana_chariot',
    name: 'The Chariot',
    number: 7,
    type: 'major',
    image: '/cards/major/major_arcana_chariot.png',
    keywords: ['control', 'willpower', 'success', 'action', 'determination'],
    upright: {
      meaning: 'Take control of your life through willpower and determination. Success comes through focused action.',
      keywords: ['control', 'willpower', 'success', 'action', 'determination'],
      description: 'The Chariot represents control, willpower, success and determination. It signifies overcoming obstacles through focused effort and self-discipline.',
    },
    reversed: {
      meaning: 'Lack of control, aggression, obstacles, self-discipline, opposition.',
      keywords: ['lack of control', 'aggression', 'obstacles', 'lack of discipline', 'opposition'],
      description: 'The Chariot reversed suggests lack of control, aggression, obstacles, lack of self-discipline and opposition.',
    },
  },
  {
    id: 'major_arcana_strength',
    name: 'Strength',
    number: 8,
    type: 'major',
    image: '/cards/major/major_arcana_strength.png',
    keywords: ['strength', 'courage', 'persuasion', 'influence', 'compassion'],
    upright: {
      meaning: 'Find strength through compassion and patience. True power comes from within.',
      keywords: ['strength', 'courage', 'persuasion', 'influence', 'compassion'],
      description: 'Strength represents inner strength, courage, persuasion and compassion. It signifies the power of gentleness and the ability to overcome challenges through patience.',
    },
    reversed: {
      meaning: 'Self-doubt, low energy, raw emotion, weakness, insecurity.',
      keywords: ['self-doubt', 'low energy', 'raw emotion', 'weakness', 'insecurity'],
      description: 'Strength reversed suggests self-doubt, low energy, raw emotion, weakness and insecurity.',
    },
  },
  {
    id: 'major_arcana_hermit',
    name: 'The Hermit',
    number: 9,
    type: 'major',
    image: '/cards/major/major_arcana_hermit.png',
    keywords: ['soul-searching', 'introspection', 'being alone', 'inner guidance', 'solitude'],
    upright: {
      meaning: 'Take time for introspection and soul-searching. Seek inner guidance through solitude.',
      keywords: ['soul-searching', 'introspection', 'being alone', 'inner guidance', 'solitude'],
      description: 'The Hermit represents soul-searching, introspection and inner guidance. He is the wise sage who has withdrawn from the world to seek truth.',
    },
    reversed: {
      meaning: 'Isolation, loneliness, withdrawal, rejection, loneliness.',
      keywords: ['isolation', 'loneliness', 'withdrawal', 'rejection', 'loneliness'],
      description: 'The Hermit reversed suggests isolation, loneliness, withdrawal, rejection and loneliness.',
    },
  },
  {
    id: 'major_arcana_fortune',
    name: 'Wheel of Fortune',
    number: 10,
    type: 'major',
    image: '/cards/major/major_arcana_fortune.png',
    keywords: ['good luck', 'karma', 'life cycles', 'destiny', 'fate'],
    upright: {
      meaning: 'Embrace the cycles of life. Good luck and positive changes are coming your way.',
      keywords: ['good luck', 'karma', 'life cycles', 'destiny', 'fate'],
      description: 'The Wheel of Fortune represents good luck, karma, life cycles and destiny. It signifies the ever-changing nature of life and the importance of going with the flow.',
    },
    reversed: {
      meaning: 'Bad luck, resistance to change, breaking cycles, inevitable fate, bad karma.',
      keywords: ['bad luck', 'resistance to change', 'breaking cycles', 'inevitable fate', 'bad karma'],
      description: 'The Wheel of Fortune reversed suggests bad luck, resistance to change, breaking cycles, inevitable fate and bad karma.',
    },
  },
  {
    id: 'major_arcana_justice',
    name: 'Justice',
    number: 11,
    type: 'major',
    image: '/cards/major/major_arcana_justice.png',
    keywords: ['justice', 'fairness', 'truth', 'cause and effect', 'law'],
    upright: {
      meaning: 'Seek justice and fairness. Truth will prevail. Your actions have consequences.',
      keywords: ['justice', 'fairness', 'truth', 'cause and effect', 'law'],
      description: 'Justice represents justice, fairness, truth and cause and effect. It signifies the importance of making fair decisions and accepting the consequences of your actions.',
    },
    reversed: {
      meaning: 'Unfairness, lack of accountability, dishonesty, unjustness, bias',
      keywords: ['unfairness', 'lack of accountability', 'dishonesty', 'unjustness', 'bias'],
      description: 'Justice reversed suggests unfairness, lack of accountability, dishonesty, unjustness and bias.',
    },
  },
  {
    id: 'major_arcana_hanged',
    name: 'The Hanged Man',
    number: 12,
    type: 'major',
    image: '/cards/major/major_arcana_hanged.png',
    keywords: ['pause', 'surrender', 'letting go', 'new perspectives', 'sacrifice'],
    upright: {
      meaning: 'Pause and surrender. Let go of control and see things from a new perspective.',
      keywords: ['pause', 'surrender', 'letting go', 'new perspectives', 'sacrifice'],
      description: 'The Hanged Man represents pause, surrender, letting go and new perspectives. It signifies the importance of sacrificing something for greater understanding.',
    },
    reversed: {
      meaning: 'Delays, resistance, stalling, indecision, stuckness',
      keywords: ['delays', 'resistance', 'stalling', 'indecision', 'stuckness'],
      description: 'The Hanged Man reversed suggests delays, resistance, stalling, indecision and stuckness.',
    },
  },
  {
    id: 'major_arcana_death',
    name: 'Death',
    number: 13,
    type: 'major',
    image: '/cards/major/major_arcana_death.png',
    keywords: ['endings', 'change', 'transformation', 'transition', 'release'],
    upright: {
      meaning: 'Embrace endings and transformation. Change is necessary for growth.',
      keywords: ['endings', 'change', 'transformation', 'transition', 'release'],
      description: 'Death represents endings, change, transformation and transition. It signifies the end of one chapter and the beginning of another.',
    },
    reversed: {
      meaning: 'Resistance to change, personal transformation, inner purging, stagnation, holding on',
      keywords: ['resistance to change', 'personal transformation', 'inner purging', 'stagnation', 'holding on'],
      description: 'Death reversed suggests resistance to change, personal transformation, inner purging, stagnation and holding on.',
    },
  },
  {
    id: 'major_arcana_temperance',
    name: 'Temperance',
    number: 14,
    type: 'major',
    image: '/cards/major/major_arcana_temperance.png',
    keywords: ['balance', 'moderation', 'patience', 'purpose', 'meaning'],
    upright: {
      meaning: 'Find balance and moderation. Practice patience and seek meaning in your life.',
      keywords: ['balance', 'moderation', 'patience', 'purpose', 'meaning'],
      description: 'Temperance represents balance, moderation, patience and purpose. It signifies the importance of finding harmony and avoiding extremes.',
    },
    reversed: {
      meaning: 'Imbalance, excess, self-healing, realignment, lack of long-term vision',
      keywords: ['imbalance', 'excess', 'self-healing', 'realignment', 'lack of long-term vision'],
      description: 'Temperance reversed suggests imbalance, excess, self-healing, realignment and lack of long-term vision.',
    },
  },
  {
    id: 'major_arcana_devil',
    name: 'The Devil',
    number: 15,
    type: 'major',
    image: '/cards/major/major_arcana_devil.png',
    keywords: ['shadow self', 'attachment', 'addiction', 'restriction', 'sexuality'],
    upright: {
      meaning: 'Confront your shadow self. Break free from attachments and addictions.',
      keywords: ['shadow self', 'attachment', 'addiction', 'restriction', 'sexuality'],
      description: 'The Devil represents the shadow self, attachment, addiction and restriction. It signifies the importance of confronting your fears and breaking free from limiting beliefs.',
    },
    reversed: {
      meaning: 'Releasing limiting beliefs, exploring dark thoughts, detachment, breaking free, inner power',
      keywords: ['releasing limiting beliefs', 'exploring dark thoughts', 'detachment', 'breaking free', 'inner power'],
      description: 'The Devil reversed suggests releasing limiting beliefs, exploring dark thoughts, detachment, breaking free and inner power.',
    },
  },
  {
    id: 'major_arcana_tower',
    name: 'The Tower',
    number: 16,
    type: 'major',
    image: '/cards/major/major_arcana_tower.png',
    keywords: ['sudden change', 'upheaval', 'chaos', 'revelation', 'awakening'],
    upright: {
      meaning: 'Embrace sudden change and upheaval. Destruction leads to revelation and awakening.',
      keywords: ['sudden change', 'upheaval', 'chaos', 'revelation', 'awakening'],
      description: 'The Tower represents sudden change, upheaval, chaos and revelation. It signifies the destruction of old structures to make way for new growth.',
    },
    reversed: {
      meaning: 'Personal transformation, fear of change, averting disaster, delayed destruction, resisting change',
      keywords: ['personal transformation', 'fear of change', 'averting disaster', 'delayed destruction', 'resisting change'],
      description: 'The Tower reversed suggests personal transformation, fear of change, averting disaster, delayed destruction and resisting change.',
    },
  },
  {
    id: 'major_arcana_star',
    name: 'The Star',
    number: 17,
    type: 'major',
    image: '/cards/major/major_arcana_star.png',
    keywords: ['hope', 'faith', 'purpose', 'renewal', 'spirituality'],
    upright: {
      meaning: 'Have hope and faith. Renew your sense of purpose and connect with your spirituality.',
      keywords: ['hope', 'faith', 'purpose', 'renewal', 'spirituality'],
      description: 'The Star represents hope, faith, purpose and renewal. It signifies a time of healing and spiritual connection after a period of darkness.',
    },
    reversed: {
      meaning: 'Lack of faith, despair, self-trust, disconnection, negativity',
      keywords: ['lack of faith', 'despair', 'self-trust', 'disconnection', 'negativity'],
      description: 'The Star reversed suggests lack of faith, despair, self-trust, disconnection and negativity.',
    },
  },
  {
    id: 'major_arcana_moon',
    name: 'The Moon',
    number: 18,
    type: 'major',
    image: '/cards/major/major_arcana_moon.png',
    keywords: ['illusion', 'fear', 'anxiety', 'subconscious', 'intuition'],
    upright: {
      meaning: 'Trust your intuition and face your fears. Illusions may cloud your judgment.',
      keywords: ['illusion', 'fear', 'anxiety', 'subconscious', 'intuition'],
      description: 'The Moon represents illusion, fear, anxiety and the subconscious. It signifies a time of uncertainty and the need to trust your inner guidance.',
    },
    reversed: {
      meaning: 'Release of fear, repressed emotions, inner confusion, lack of clarity, uncovering the truth',
      keywords: ['release of fear', 'repressed emotions', 'inner confusion', 'lack of clarity', 'uncovering the truth'],
      description: 'The Moon reversed suggests release of fear, repressed emotions, inner confusion, lack of clarity and uncovering the truth.',
    },
  },
  {
    id: 'major_arcana_sun',
    name: 'The Sun',
    number: 19,
    type: 'major',
    image: '/cards/major/major_arcana_sun.png',
    keywords: ['positivity', 'fun', 'warmth', 'success', 'vitality'],
    upright: {
      meaning: 'Embrace positivity and joy. Success and vitality are yours to claim.',
      keywords: ['positivity', 'fun', 'warmth', 'success', 'vitality'],
      description: 'The Sun represents positivity, fun, warmth and success. It signifies a time of joy, vitality and achievement.',
    },
    reversed: {
      meaning: 'Inner child, feeling down, optimism, depression, lack of success',
      keywords: ['inner child', 'feeling down', 'optimism', 'depression', 'lack of success'],
      description: 'The Sun reversed suggests inner child, feeling down, optimism, depression and lack of success.',
    },
  },
  {
    id: 'major_arcana_judgement',
    name: 'Judgement',
    number: 20,
    type: 'major',
    image: '/cards/major/major_arcana_judgement.png',
    keywords: ['judgement', 'rebirth', 'inner calling', 'absolution', 'reflection'],
    upright: {
      meaning: 'Embrace judgement and rebirth. Answer your inner calling and seek absolution.',
      keywords: ['judgement', 'rebirth', 'inner calling', 'absolution', 'reflection'],
      description: 'Judgement represents judgement, rebirth, inner calling and absolution. It signifies a time of reflection and the opportunity for spiritual awakening.',
    },
    reversed: {
      meaning: 'Self-doubt, inner critic, ignoring the call, refusing to learn, lack of self-awareness',
      keywords: ['self-doubt', 'inner critic', 'ignoring the call', 'refusing to learn', 'lack of self-awareness'],
      description: 'Judgement reversed suggests self-doubt, inner critic, ignoring the call, refusing to learn and lack of self-awareness.',
    },
  },
  {
    id: 'major_arcana_world',
    name: 'The World',
    number: 21,
    type: 'major',
    image: '/cards/major/major_arcana_world.png',
    keywords: ['completion', 'integration', 'accomplishment', 'travel', 'fulfillment'],
    upright: {
      meaning: 'Celebrate completion and accomplishment. You have achieved fulfillment and integration.',
      keywords: ['completion', 'integration', 'accomplishment', 'travel', 'fulfillment'],
      description: 'The World represents completion, integration, accomplishment and fulfillment. It signifies the end of a journey and the achievement of your goals.',
    },
    reversed: {
      meaning: 'Seeking closure,  shortcuts, incomplete, no closure, emptiness',
      keywords: ['seeking closure', 'shortcuts', 'incomplete', 'no closure', 'emptiness'],
      description: 'The World reversed suggests seeking closure, shortcuts, incomplete, no closure and emptiness.',
    },
  },

  // Minor Arcana - Wands (14 cards)
  {
    id: 'minor_arcana_wands_ace',
    name: 'Ace of Wands',
    number: 1,
    type: 'minor',
    suit: 'wands',
    image: '/cards/minor/minor_arcana_wands_ace.png',
    keywords: ['inspiration', 'new opportunities', 'growth', 'potential', 'new beginnings'],
    upright: {
      meaning: 'A new opportunity or creative spark is coming your way. Seize it with enthusiasm.',
      keywords: ['inspiration', 'new opportunities', 'growth', 'potential', 'new beginnings'],
      description: 'The Ace of Wands represents inspiration, new opportunities and creative potential. It signifies the start of a new venture or creative project.',
    },
    reversed: {
      meaning: 'Delays, lack of motivation, creative block, slowed momentum, bad timing',
      keywords: ['delays', 'lack of motivation', 'creative block', 'slowed momentum', 'bad timing'],
      description: 'The Ace of Wands reversed suggests delays, lack of motivation, creative block, slowed momentum and bad timing.',
    },
  },
  {
    id: 'minor_arcana_wands_2',
    name: 'Two of Wands',
    number: 2,
    type: 'minor',
    suit: 'wands',
    image: '/cards/minor/minor_arcana_wands_2.png',
    keywords: ['future planning', 'progress', 'decisions', 'discovery', 'decisions'],
    upright: {
      meaning: 'Plan for the future and make important decisions. Progress is on the horizon.',
      keywords: ['future planning', 'progress', 'decisions', 'discovery', 'decisions'],
      description: 'The Two of Wands represents future planning, progress and decision-making. It signifies the need to look ahead and prepare for what\'s coming.',
    },
    reversed: {
      meaning: 'Fear of the unknown, playing it safe, lack of planning, indecision, fear of leaving comfort zone',
      keywords: ['fear of the unknown', 'playing it safe', 'lack of planning', 'indecision', 'fear of leaving comfort zone'],
      description: 'The Two of Wands reversed suggests fear of the unknown, playing it safe, lack of planning, indecision and fear of leaving comfort zone.',
    },
  },
  {
    id: 'minor_arcana_wands_3',
    name: 'Three of Wands',
    number: 3,
    type: 'minor',
    suit: 'wands',
    image: '/cards/minor/minor_arcana_wands_3.png',
    keywords: ['progress', 'expansion', 'foresight', 'overseas opportunities', 'business'],
    upright: {
      meaning: 'Progress and expansion are coming. Look for opportunities beyond your current situation.',
      keywords: ['progress', 'expansion', 'foresight', 'overseas opportunities', 'business'],
      description: 'The Three of Wands represents progress, expansion and foresight. It signifies growth and opportunities on the horizon.',
    },
    reversed: {
      meaning: 'Lack of foresight, short-term focus, delays, frustration, obstacles',
      keywords: ['lack of foresight', 'short-term focus', 'delays', 'frustration', 'obstacles'],
      description: 'The Three of Wands reversed suggests lack of foresight, short-term focus, delays, frustration and obstacles.',
    },
  },
  {
    id: 'minor_arcana_wands_4',
    name: 'Four of Wands',
    number: 4,
    type: 'minor',
    suit: 'wands',
    image: '/cards/minor/minor_arcana_wands_4.png',
    keywords: ['celebration', 'joy', 'harmony', 'relaxation', 'homecoming'],
    upright: {
      meaning: 'Celebrate and enjoy the moment. Harmony and joy surround you.',
      keywords: ['celebration', 'joy', 'harmony', 'relaxation', 'homecoming'],
      description: 'The Four of Wands represents celebration, joy and harmony. It signifies a time of happiness and community.',
    },
    reversed: {
      meaning: 'Lack of harmony, tension, transition, lack of stability, misalignment',
      keywords: ['lack of harmony', 'tension', 'transition', 'lack of stability', 'misalignment'],
      description: 'The Four of Wands reversed suggests lack of harmony, tension, transition, lack of stability and misalignment.',
    },
  },
  {
    id: 'minor_arcana_wands_5',
    name: 'Five of Wands',
    number: 5,
    type: 'minor',
    suit: 'wands',
    image: '/cards/minor/minor_arcana_wands_5.png',
    keywords: ['conflict', 'disagreements', 'competition', 'tension', 'clash'],
    upright: {
      meaning: 'Face conflicts and disagreements head-on. Competition can lead to growth.',
      keywords: ['conflict', 'disagreements', 'competition', 'tension', 'clash'],
      description: 'The Five of Wands represents conflict, disagreements and competition. It signifies challenges that must be overcome.',
    },
    reversed: {
      meaning: 'Avoiding conflict, inner conflict, tension, release of conflict, walking away',
      keywords: ['avoiding conflict', 'inner conflict', 'tension', 'release of conflict', 'walking away'],
      description: 'The Five of Wands reversed suggests avoiding conflict, inner conflict, tension, release of conflict and walking away.',
    },
  },
  {
    id: 'minor_arcana_wands_6',
    name: 'Six of Wands',
    number: 6,
    type: 'minor',
    suit: 'wands',
    image: '/cards/minor/minor_arcana_wands_6.png',
    keywords: ['success', 'public recognition', 'progress', 'confidence', 'victory'],
    upright: {
      meaning: 'Celebrate your success and public recognition. Confidence and victory are yours.',
      keywords: ['success', 'public recognition', 'progress', 'confidence', 'victory'],
      description: 'The Six of Wands represents success, public recognition and victory. It signifies achievement and the recognition of your efforts.',
    },
    reversed: {
      meaning: 'Ego, fall from grace, lack of confidence, disappointment, arrogance',
      keywords: ['ego', 'fall from grace', 'lack of confidence', 'disappointment', 'arrogance'],
      description: 'The Six of Wands reversed suggests ego, fall from grace, lack of confidence, disappointment and arrogance.',
    },
  },
  {
    id: 'minor_arcana_wands_7',
    name: 'Seven of Wands',
    number: 7,
    type: 'minor',
    suit: 'wands',
    image: '/cards/minor/minor_arcana_wands_7.png',
    keywords: ['challenge', 'competition', 'protection', 'perseverance', 'standing ground'],
    upright: {
      meaning: 'Stand your ground and defend your position. Perseverance will lead to success.',
      keywords: ['challenge', 'competition', 'protection', 'perseverance', 'standing ground'],
      description: 'The Seven of Wands represents challenge, competition and perseverance. It signifies the need to defend your position and stay strong.',
    },
    reversed: {
      meaning: 'Feeling overwhelmed, giving up, too much pressure, defensive, exhaustion',
      keywords: ['feeling overwhelmed', 'giving up', 'too much pressure', 'defensive', 'exhaustion'],
      description: 'The Seven of Wands reversed suggests feeling overwhelmed, giving up, too much pressure, defensive and exhaustion.',
    },
  },
  {
    id: 'minor_arcana_wands_8',
    name: 'Eight of Wands',
    number: 8,
    type: 'minor',
    suit: 'wands',
    image: '/cards/minor/minor_arcana_wands_8.png',
    keywords: ['movement', 'fast paced change', 'action', 'alignment', 'travel'],
    upright: {
      meaning: 'Movement and fast-paced change are coming. Take action and align with your goals.',
      keywords: ['movement', 'fast paced change', 'action', 'alignment', 'travel'],
      description: 'The Eight of Wands represents movement, fast-paced change and action. It signifies rapid progress and the need to act quickly.',
    },
    reversed: {
      meaning: 'Delays, frustration, slowing down, lack of movement, misalignment',
      keywords: ['delays', 'frustration', 'slowing down', 'lack of movement', 'misalignment'],
      description: 'The Eight of Wands reversed suggests delays, frustration, slowing down, lack of movement and misalignment.',
    },
  },
  {
    id: 'minor_arcana_wands_9',
    name: 'Nine of Wands',
    number: 9,
    type: 'minor',
    suit: 'wands',
    image: '/cards/minor/minor_arcana_wands_9.png',
    keywords: ['resilience', 'courage', 'persistence', 'test of faith', 'exhaustion'],
    upright: {
      meaning: 'Stay resilient and courageous. Persistence will help you overcome challenges.',
      keywords: ['resilience', 'courage', 'persistence', 'test of faith', 'exhaustion'],
      description: 'The Nine of Wands represents resilience, courage and persistence. It signifies the need to stay strong despite challenges.',
    },
    reversed: {
      meaning: 'Paranoia, exhaustion, struggling, lack of resilience, giving up',
      keywords: ['paranoia', 'exhaustion', 'struggling', 'lack of resilience', 'giving up'],
      description: 'The Nine of Wands reversed suggests paranoia, exhaustion, struggling, lack of resilience and giving up.',
    },
  },
  {
    id: 'minor_arcana_wands_10',
    name: 'Ten of Wands',
    number: 10,
    type: 'minor',
    suit: 'wands',
    image: '/cards/minor/minor_arcana_wands_10.png',
    keywords: ['burden', 'extra responsibility', 'hard work', 'completion', 'overwhelmed'],
    upright: {
      meaning: 'You may feel burdened by extra responsibility. Hard work will lead to completion.',
      keywords: ['burden', 'extra responsibility', 'hard work', 'completion', 'overwhelmed'],
      description: 'The Ten of Wands represents burden, extra responsibility and hard work. It signifies the weight of responsibilities and the need to push through to completion.',
    },
    reversed: {
      meaning: 'Releasing burden, delegating, burnout, stress, overwhelmed',
      keywords: ['releasing burden', 'delegating', 'burnout', 'stress', 'overwhelmed'],
      description: 'The Ten of Wands reversed suggests releasing burden, delegating, burnout, stress and being overwhelmed.',
    },
  },
  {
    id: 'minor_arcana_wands_page',
    name: 'Page of Wands',
    number: 11,
    type: 'minor',
    suit: 'wands',
    court: 'page',
    image: '/cards/minor/minor_arcana_wands_page.png',
    keywords: ['inspiration', 'ideas', 'discovery', 'limitless potential', 'free spirit'],
    upright: {
      meaning: 'Embrace inspiration and new ideas. Your potential is limitless.',
      keywords: ['inspiration', 'ideas', 'discovery', 'limitless potential', 'free spirit'],
      description: 'The Page of Wands represents inspiration, ideas and discovery. It signifies a free spirit with limitless potential.',
    },
    reversed: {
      meaning: 'Procrastination, lack of motivation, boredom, creative block, distraction',
      keywords: ['procrastination', 'lack of motivation', 'boredom', 'creative block', 'distraction'],
      description: 'The Page of Wands reversed suggests procrastination, lack of motivation, boredom, creative block and distraction.',
    },
  },
  {
    id: 'minor_arcana_wands_knight',
    name: 'Knight of Wands',
    number: 12,
    type: 'minor',
    suit: 'wands',
    court: 'knight',
    image: '/cards/minor/minor_arcana_wands_knight.png',
    keywords: ['energy', 'passion', 'inspired action', 'adventure', 'impulsiveness'],
    upright: {
      meaning: 'Channel your energy and passion into inspired action. Adventure awaits.',
      keywords: ['energy', 'passion', 'inspired action', 'adventure', 'impulsiveness'],
      description: 'The Knight of Wands represents energy, passion and inspired action. He is the adventurer who charges forward with enthusiasm.',
    },
    reversed: {
      meaning: 'Haste, impulsiveness, rash decisions, burnout, lack of direction',
      keywords: ['haste', 'impulsiveness', 'rash decisions', 'burnout', 'lack of direction'],
      description: 'The Knight of Wands reversed suggests haste, impulsiveness, rash decisions, burnout and lack of direction.',
    },
  },
  {
    id: 'minor_arcana_wands_queen',
    name: 'Queen of Wands',
    number: 13,
    type: 'minor',
    suit: 'wands',
    court: 'queen',
    image: '/cards/minor/minor_arcana_wands_queen.png',
    keywords: ['courage', 'confidence', 'independence', 'social butterfly', 'determination'],
    upright: {
      meaning: 'Embrace your courage and confidence. Independence and determination will lead to success.',
      keywords: ['courage', 'confidence', 'independence', 'social butterfly', 'determination'],
      description: 'The Queen of Wands represents courage, confidence and independence. She is the social butterfly who radiates warmth and determination.',
    },
    reversed: {
      meaning: 'Selfishness, jealousy, insecurity, controlling, demanding',
      keywords: ['selfishness', 'jealousy', 'insecurity', 'controlling', 'demanding'],
      description: 'The Queen of Wands reversed suggests selfishness, jealousy, insecurity, controlling and demanding behavior.',
    },
  },
  {
    id: 'minor_arcana_wands_king',
    name: 'King of Wands',
    number: 14,
    type: 'minor',
    suit: 'wands',
    court: 'king',
    image: '/cards/minor/minor_arcana_wands_king.png',
    keywords: ['natural born leader', 'vision', 'entrepreneur', 'honour', 'risk-taker'],
    upright: {
      meaning: 'Lead with vision and honor. Take calculated risks as an entrepreneur.',
      keywords: ['natural born leader', 'vision', 'entrepreneur', 'honour', 'risk-taker'],
      description: 'The King of Wands represents natural born leadership, vision and entrepreneurship. He is the risk-taker who leads with honor.',
    },
    reversed: {
      meaning: 'Arrogance, impulsiveness, short-tempered, controlling, aggressive',
      keywords: ['arrogance', 'impulsiveness', 'short-tempered', 'controlling', 'aggressive'],
      description: 'The King of Wands reversed suggests arrogance, impulsiveness, short-tempered, controlling and aggressive behavior.',
    },
  },

  // Minor Arcana - Cups (14 cards)
  {
    id: 'minor_arcana_cups_ace',
    name: 'Ace of Cups',
    number: 1,
    type: 'minor',
    suit: 'cups',
    image: '/cards/minor/minor_arcana_cups_ace.png',
    keywords: ['love', 'new relationships', 'compassion', 'creativity', 'intuition'],
    upright: {
      meaning: 'Open your heart to love and new relationships. Compassion and creativity flow through you.',
      keywords: ['love', 'new relationships', 'compassion', 'creativity', 'intuition'],
      description: 'The Ace of Cups represents love, new relationships and compassion. It signifies the opening of the heart to emotional fulfillment.',
    },
    reversed: {
      meaning: 'Blocked emotions, rejection, emotional instability, lack of creativity, emptiness',
      keywords: ['blocked emotions', 'rejection', 'emotional instability', 'lack of creativity', 'emptiness'],
      description: 'The Ace of Cups reversed suggests blocked emotions, rejection, emotional instability, lack of creativity and emptiness.',
    },
  },
  {
    id: 'minor_arcana_cups_2',
    name: 'Two of Cups',
    number: 2,
    type: 'minor',
    suit: 'cups',
    image: '/cards/minor/minor_arcana_cups_2.png',
    keywords: ['unified love', 'partnership', 'mutual attraction', 'relationships', 'connection'],
    upright: {
      meaning: 'Experience unified love and partnership. Mutual attraction strengthens your connection.',
      keywords: ['unified love', 'partnership', 'mutual attraction', 'relationships', 'connection'],
      description: 'The Two of Cups represents unified love, partnership and mutual attraction. It signifies a deep connection between two people.',
    },
    reversed: {
      meaning: 'Break-up, lack of harmony, imbalance, misalignment, disconnection',
      keywords: ['break-up', 'lack of harmony', 'imbalance', 'misalignment', 'disconnection'],
      description: 'The Two of Cups reversed suggests break-up, lack of harmony, imbalance, misalignment and disconnection.',
    },
  },
  {
    id: 'minor_arcana_cups_3',
    name: 'Three of Cups',
    number: 3,
    type: 'minor',
    suit: 'cups',
    image: '/cards/minor/minor_arcana_cups_3.png',
    keywords: ['celebration', 'friendship', 'creativity', 'collaborations', 'community'],
    upright: {
      meaning: 'Celebrate with friends and community. Creativity flourishes through collaboration.',
      keywords: ['celebration', 'friendship', 'creativity', 'collaborations', 'community'],
      description: 'The Three of Cups represents celebration, friendship and creativity. It signifies joy and connection with others.',
    },
    reversed: {
      meaning: 'Overindulgence, gossip, isolation, loneliness, excessive partying',
      keywords: ['overindulgence', 'gossip', 'isolation', 'loneliness', 'excessive partying'],
      description: 'The Three of Cups reversed suggests overindulgence, gossip, isolation, loneliness and excessive partying.',
    },
  },
  {
    id: 'minor_arcana_cups_4',
    name: 'Four of Cups',
    number: 4,
    type: 'minor',
    suit: 'cups',
    image: '/cards/minor/minor_arcana_cups_4.png',
    keywords: ['meditation', 'contemplation', 'apathy', 'reevaluation', 'disconnection'],
    upright: {
      meaning: 'Take time for meditation and contemplation. Reevaluate your connections.',
      keywords: ['meditation', 'contemplation', 'apathy', 'reevaluation', 'disconnection'],
      description: 'The Four of Cups represents meditation, contemplation and reevaluation. It signifies a time of introspection and disconnection from the outside world.',
    },
    reversed: {
      meaning: 'Withdrawal, reconnecting, introspection, isolation, depression',
      keywords: ['withdrawal', 'reconnecting', 'introspection', 'isolation', 'depression'],
      description: 'The Four of Cups reversed suggests withdrawal, reconnecting, introspection, isolation and depression.',
    },
  },
  {
    id: 'minor_arcana_cups_5',
    name: 'Five of Cups',
    number: 5,
    type: 'minor',
    suit: 'cups',
    image: '/cards/minor/minor_arcana_cups_5.png',
    keywords: ['regret', 'failure', 'disappointment', 'pessimism', 'loss'],
    upright: {
      meaning: 'Face regret and disappointment. Learn from failure and move forward.',
      keywords: ['regret', 'failure', 'disappointment', 'pessimism', 'loss'],
      description: 'The Five of Cups represents regret, failure and disappointment. It signifies the need to accept loss and move forward.',
    },
    reversed: {
      meaning: 'Acceptance, moving on, finding peace, forgiveness, release',
      keywords: ['acceptance', 'moving on', 'finding peace', 'forgiveness', 'release'],
      description: 'The Five of Cups reversed suggests acceptance, moving on, finding peace, forgiveness and release.',
    },
  },
  {
    id: 'minor_arcana_cups_6',
    name: 'Six of Cups',
    number: 6,
    type: 'minor',
    suit: 'cups',
    image: '/cards/minor/minor_arcana_cups_6.png',
    keywords: ['revisiting the past', 'childhood memories', 'innocence', 'joy', 'nostalgia'],
    upright: {
      meaning: 'Revisit the past with nostalgia. Childhood memories bring joy and innocence.',
      keywords: ['revisiting the past', 'childhood memories', 'innocence', 'joy', 'nostalgia'],
      description: 'The Six of Cups represents revisiting the past, childhood memories and innocence. It signifies nostalgia and the joy of simpler times.',
    },
    reversed: {
      meaning: 'Moving forward, leaving the past, personal growth, breaking free, releasing memories',
      keywords: ['moving forward', 'leaving the past', 'personal growth', 'breaking free', 'releasing memories'],
      description: 'The Six of Cups reversed suggests moving forward, leaving the past, personal growth, breaking free and releasing memories.',
    },
  },
  {
    id: 'minor_arcana_cups_7',
    name: 'Seven of Cups',
    number: 7,
    type: 'minor',
    suit: 'cups',
    image: '/cards/minor/minor_arcana_cups_7.png',
    keywords: ['opportunities', 'choices', 'wishful thinking', 'illusion', 'fantasy'],
    upright: {
      meaning: 'Many opportunities and choices await. Avoid wishful thinking and illusion.',
      keywords: ['opportunities', 'choices', 'wishful thinking', 'illusion', 'fantasy'],
      description: 'The Seven of Cups represents opportunities, choices and wishful thinking. It signifies the need to distinguish between reality and fantasy.',
    },
    reversed: {
      meaning: 'Clarity, making a decision, commitment, focus, determination',
      keywords: ['clarity', 'making a decision', 'commitment', 'focus', 'determination'],
      description: 'The Seven of Cups reversed suggests clarity, making a decision, commitment, focus and determination.',
    },
  },
  {
    id: 'minor_arcana_cups_8',
    name: 'Eight of Cups',
    number: 8,
    type: 'minor',
    suit: 'cups',
    image: '/cards/minor/minor_arcana_cups_8.png',
    keywords: ['disappointment', 'abandonment', 'withdrawal', 'escapism', 'walking away'],
    upright: {
      meaning: 'Face disappointment and walk away. Withdrawal may be necessary for growth.',
      keywords: ['disappointment', 'abandonment', 'withdrawal', 'escapism', 'walking away'],
      description: 'The Eight of Cups represents disappointment, abandonment and withdrawal. It signifies the need to leave behind what no longer serves you.',
    },
    reversed: {
      meaning: 'Fear of change, staying in comfort zone, avoidance, fear of the unknown, lack of direction',
      keywords: ['fear of change', 'staying in comfort zone', 'avoidance', 'fear of the unknown', 'lack of direction'],
      description: 'The Eight of Cups reversed suggests fear of change, staying in comfort zone, avoidance, fear of the unknown and lack of direction.',
    },
  },
  {
    id: 'minor_arcana_cups_9',
    name: 'Nine of Cups',
    number: 9,
    type: 'minor',
    suit: 'cups',
    image: '/cards/minor/minor_arcana_cups_9.png',
    keywords: ['contentment', 'satisfaction', 'gratitude', 'wish come true', 'abundance'],
    upright: {
      meaning: 'Experience contentment and satisfaction. Your wishes have come true.',
      keywords: ['contentment', 'satisfaction', 'gratitude', 'wish come true', 'abundance'],
      description: 'The Nine of Cups represents contentment, satisfaction and gratitude. It signifies the fulfillment of desires and emotional abundance.',
    },
    reversed: {
      meaning: 'Smugness, arrogance, materialism, self-indulgence, lack of gratitude',
      keywords: ['smugness', 'arrogance', 'materialism', 'self-indulgence', 'lack of gratitude'],
      description: 'The Nine of Cups reversed suggests smugness, arrogance, materialism, self-indulgence and lack of gratitude.',
    },
  },
  {
    id: 'minor_arcana_cups_10',
    name: 'Ten of Cups',
    number: 10,
    type: 'minor',
    suit: 'cups',
    image: '/cards/minor/minor_arcana_cups_10.png',
    keywords: ['divine love', 'blissful relationships', 'harmony', 'alignment', 'joy'],
    upright: {
      meaning: 'Experience divine love and blissful relationships. Harmony and joy fill your life.',
      keywords: ['divine love', 'blissful relationships', 'harmony', 'alignment', 'joy'],
      description: 'The Ten of Cups represents divine love, blissful relationships and harmony. It signifies emotional fulfillment and family happiness.',
    },
    reversed: {
      meaning: 'Broken family, domestic issues, misalignment, conflict, disconnection',
      keywords: ['broken family', 'domestic issues', 'misalignment', 'conflict', 'disconnection'],
      description: 'The Ten of Cups reversed suggests broken family, domestic issues, misalignment, conflict and disconnection.',
    },
  },
  {
    id: 'minor_arcana_cups_page',
    name: 'Page of Cups',
    number: 11,
    type: 'minor',
    suit: 'cups',
    court: 'page',
    image: '/cards/minor/minor_arcana_cups_page.png',
    keywords: ['creative opportunities', 'intuitive messages', 'curiosity', 'wonder', 'exploration of emotions'],
    upright: {
      meaning: 'Embrace creative opportunities and intuitive messages. Curiosity leads to wonder.',
      keywords: ['creative opportunities', 'intuitive messages', 'curiosity', 'wonder', 'exploration of emotions'],
      description: 'The Page of Cups represents creative opportunities, intuitive messages and curiosity. He is the explorer of emotions and the messenger of the heart.',
    },
    reversed: {
      meaning: 'Emotional insecurity, disappointment, blocked creativity, immaturity, emotional volatility',
      keywords: ['emotional insecurity', 'disappointment', 'blocked creativity', 'immaturity', 'emotional volatility'],
      description: 'The Page of Cups reversed suggests emotional insecurity, disappointment, blocked creativity, immaturity and emotional volatility.',
    },
  },
  {
    id: 'minor_arcana_cups_knight',
    name: 'Knight of Cups',
    number: 12,
    type: 'minor',
    suit: 'cups',
    court: 'knight',
    image: '/cards/minor/minor_arcana_cups_knight.png',
    keywords: ['creativity', 'romance', 'charm', 'imagination', 'beauty'],
    upright: {
      meaning: 'Express your creativity and romance. Charm and imagination guide your path.',
      keywords: ['creativity', 'romance', 'charm', 'imagination', 'beauty'],
      description: 'The Knight of Cups represents creativity, romance and charm. He is the romantic who follows his heart and imagination.',
    },
    reversed: {
      meaning: 'Moodiness, emotional manipulation, unrealistic expectations, disappointment, insecurity',
      keywords: ['moodiness', 'emotional manipulation', 'unrealistic expectations', 'disappointment', 'insecurity'],
      description: 'The Knight of Cups reversed suggests moodiness, emotional manipulation, unrealistic expectations, disappointment and insecurity.',
    },
  },
  {
    id: 'minor_arcana_cups_queen',
    name: 'Queen of Cups',
    number: 13,
    type: 'minor',
    suit: 'cups',
    court: 'queen',
    image: '/cards/minor/minor_arcana_cups_queen.png',
    keywords: ['compassionate', 'caring', 'emotionally stable', 'intuitive', 'in flow'],
    upright: {
      meaning: 'Embrace compassion and emotional stability. Intuition guides your flow.',
      keywords: ['compassionate', 'caring', 'emotionally stable', 'intuitive', 'in flow'],
      description: 'The Queen of Cups represents compassion, caring and emotional stability. She is the intuitive healer who flows with emotions.',
    },
    reversed: {
      meaning: 'Co-dependency, emotional insecurity, overwhelming emotions, neediness, manipulation',
      keywords: ['co-dependency', 'emotional insecurity', 'overwhelming emotions', 'neediness', 'manipulation'],
      description: 'The Queen of Cups reversed suggests co-dependency, emotional insecurity, overwhelming emotions, neediness and manipulation.',
    },
  },
  {
    id: 'minor_arcana_cups_king',
    name: 'King of Cups',
    number: 14,
    type: 'minor',
    suit: 'cups',
    court: 'king',
    image: '/cards/minor/minor_arcana_cups_king.png',
    keywords: ['emotionally balanced', 'compassionate', 'diplomatic', 'calm', 'caring'],
    upright: {
      meaning: 'Maintain emotional balance and compassion. Diplomacy and calm guide your actions.',
      keywords: ['emotionally balanced', 'compassionate', 'diplomatic', 'calm', 'caring'],
      description: 'The King of Cups represents emotional balance, compassion and diplomacy. He is the calm leader who cares deeply for others.',
    },
    reversed: {
      meaning: 'Emotional manipulation, moodiness, volatility, lack of emotional control, suppressed emotions',
      keywords: ['emotional manipulation', 'moodiness', 'volatility', 'lack of emotional control', 'suppressed emotions'],
      description: 'The King of Cups reversed suggests emotional manipulation, moodiness, volatility, lack of emotional control and suppressed emotions.',
    },
  },

  // Minor Arcana - Swords (14 cards)
  {
    id: 'minor_arcana_swords_ace',
    name: 'Ace of Swords',
    number: 1,
    type: 'minor',
    suit: 'swords',
    image: '/cards/minor/minor_arcana_swords_ace.png',
    keywords: ['breakthroughs', 'new ideas', 'mental clarity', 'success', 'truth'],
    upright: {
      meaning: 'Experience breakthroughs and new ideas. Mental clarity leads to success and truth.',
      keywords: ['breakthroughs', 'new ideas', 'mental clarity', 'success', 'truth'],
      description: 'The Ace of Swords represents breakthroughs, new ideas and mental clarity. It signifies the power of the mind to cut through confusion.',
    },
    reversed: {
      meaning: 'Mental confusion, lack of clarity, chaos, distorted thinking, mental blocks',
      keywords: ['mental confusion', 'lack of clarity', 'chaos', 'distorted thinking', 'mental blocks'],
      description: 'The Ace of Swords reversed suggests mental confusion, lack of clarity, chaos, distorted thinking and mental blocks.',
    },
  },
  {
    id: 'minor_arcana_swords_2',
    name: 'Two of Swords',
    number: 2,
    type: 'minor',
    suit: 'swords',
    image: '/cards/minor/minor_arcana_swords_2.png',
    keywords: ['difficult decisions', 'weighing options', 'an impasse', 'avoidance', 'an impasse'],
    upright: {
      meaning: 'Face difficult decisions by weighing your options. Avoidance only prolongs the impasse.',
      keywords: ['difficult decisions', 'weighing options', 'an impasse', 'avoidance', 'an impasse'],
      description: 'The Two of Swords represents difficult decisions, weighing options and avoidance. It signifies the need to make a choice despite uncertainty.',
    },
    reversed: {
      meaning: 'Information overload, analysis paralysis, fear of making a decision, confusion, indecision',
      keywords: ['information overload', 'analysis paralysis', 'fear of making a decision', 'confusion', 'indecision'],
      description: 'The Two of Swords reversed suggests information overload, analysis paralysis, fear of making a decision, confusion and indecision.',
    },
  },
  {
    id: 'minor_arcana_swords_3',
    name: 'Three of Swords',
    number: 3,
    type: 'minor',
    suit: 'swords',
    image: '/cards/minor/minor_arcana_swords_3.png',
    keywords: ['heartbreak', 'emotional pain', 'sorrow', 'grief', 'hurt'],
    upright: {
      meaning: 'Face heartbreak and emotional pain. Sorrow and grief are part of the healing process.',
      keywords: ['heartbreak', 'emotional pain', 'sorrow', 'grief', 'hurt'],
      description: 'The Three of Swords represents heartbreak, emotional pain and sorrow. It signifies the pain of loss and the need to heal.',
    },
    reversed: {
      meaning: 'Recovery, releasing pain, moving on, forgiveness, healing',
      keywords: ['recovery', 'releasing pain', 'moving on', 'forgiveness', 'healing'],
      description: 'The Three of Swords reversed suggests recovery, releasing pain, moving on, forgiveness and healing.',
    },
  },
  {
    id: 'minor_arcana_swords_4',
    name: 'Four of Swords',
    number: 4,
    type: 'minor',
    suit: 'swords',
    image: '/cards/minor/minor_arcana_swords_4.png',
    keywords: ['rest', 'relaxation', 'meditation', 'contemplation', 'recuperation'],
    upright: {
      meaning: 'Take time for rest and relaxation. Meditation and contemplation bring peace.',
      keywords: ['rest', 'relaxation', 'meditation', 'contemplation', 'recuperation'],
      description: 'The Four of Swords represents rest, relaxation and meditation. It signifies the need to withdraw and recharge.',
    },
    reversed: {
      meaning: 'Restlessness, anxiety, exhaustion, burnout, stress',
      keywords: ['restlessness', 'anxiety', 'exhaustion', 'burnout', 'stress'],
      description: 'The Four of Swords reversed suggests restlessness, anxiety, exhaustion, burnout and stress.',
    },
  },
  {
    id: 'minor_arcana_swords_5',
    name: 'Five of Swords',
    number: 5,
    type: 'minor',
    suit: 'swords',
    image: '/cards/minor/minor_arcana_swords_5.png',
    keywords: ['conflict', 'disagreements', 'competition', 'defeat', 'winning at all costs'],
    upright: {
      meaning: 'Face conflict and disagreements. Competition may lead to defeat or victory.',
      keywords: ['conflict', 'disagreements', 'competition', 'defeat', 'winning at all costs'],
      description: 'The Five of Swords represents conflict, disagreements and competition. It signifies the tension between winning and losing.',
    },
    reversed: {
      meaning: 'Moving on, reconciliation, putting the past behind, forgiveness, letting go',
      keywords: ['moving on', 'reconciliation', 'putting the past behind', 'forgiveness', 'letting go'],
      description: 'The Five of Swords reversed suggests moving on, reconciliation, putting the past behind, forgiveness and letting go.',
    },
  },
  {
    id: 'minor_arcana_swords_6',
    name: 'Six of Swords',
    number: 6,
    type: 'minor',
    suit: 'swords',
    image: '/cards/minor/minor_arcana_swords_6.png',
    keywords: ['transition', 'change', 'rite of passage', 'releasing baggage', 'moving on'],
    upright: {
      meaning: 'Embrace transition and change. Release baggage and move on to new horizons.',
      keywords: ['transition', 'change', 'rite of passage', 'releasing baggage', 'moving on'],
      description: 'The Six of Swords represents transition, change and moving on. It signifies the journey from troubled waters to calmer seas.',
    },
    reversed: {
      meaning: 'Resistance to change, being stuck, personal transition, unresolved issues, slow recovery',
      keywords: ['resistance to change', 'being stuck', 'personal transition', 'unresolved issues', 'slow recovery'],
      description: 'The Six of Swords reversed suggests resistance to change, being stuck, personal transition, unresolved issues and slow recovery.',
    },
  },
  {
    id: 'minor_arcana_swords_7',
    name: 'Seven of Swords',
    number: 7,
    type: 'minor',
    suit: 'swords',
    image: '/cards/minor/minor_arcana_swords_7.png',
    keywords: ['betrayal', 'deception', 'getting away with something', 'acting strategically', 'unethical behavior'],
    upright: {
      meaning: 'Be aware of betrayal and deception. Strategic thinking may lead to success.',
      keywords: ['betrayal', 'deception', 'getting away with something', 'acting strategically', 'unethical behavior'],
      description: 'The Seven of Swords represents betrayal, deception and strategic thinking. It signifies the temptation to take shortcuts or deceive others.',
    },
    reversed: {
      meaning: 'coming clean, fessing up, apologizing, rebuilding trust, honesty',
      keywords: ['coming clean', 'fessing up', 'apologizing', 'rebuilding trust', 'honesty'],
      description: 'The Seven of Swords reversed suggests coming clean, fessing up, apologizing, rebuilding trust and honesty.',
    },
  },
  {
    id: 'minor_arcana_swords_8',
    name: 'Eight of Swords',
    number: 8,
    type: 'minor',
    suit: 'swords',
    image: '/cards/minor/minor_arcana_swords_8.png',
    keywords: ['negative thoughts', 'self-imposed restriction', 'imprisonment', 'victim mentality', 'entrapment'],
    upright: {
      meaning: 'Break free from negative thoughts and self-imposed restrictions. You are not a victim.',
      keywords: ['negative thoughts', 'self-imposed restriction', 'imprisonment', 'victim mentality', 'entrapment'],
      description: 'The Eight of Swords represents negative thoughts, self-imposed restriction and victim mentality. It signifies the feeling of being trapped by one\'s own mind.',
    },
    reversed: {
      meaning: 'Releasing limiting beliefs, mental freedom, new perspectives, open-mindedness, liberation',
      keywords: ['releasing limiting beliefs', 'mental freedom', 'new perspectives', 'open-mindedness', 'liberation'],
      description: 'The Eight of Swords reversed suggests releasing limiting beliefs, mental freedom, new perspectives, open-mindedness and liberation.',
    },
  },
  {
    id: 'minor_arcana_swords_9',
    name: 'Nine of Swords',
    number: 9,
    type: 'minor',
    suit: 'swords',
    image: '/cards/minor/minor_arcana_swords_9.png',
    keywords: ['anxiety', 'worry', 'fear', 'depression', 'nightmares'],
    upright: {
      meaning: 'Face anxiety and worry. Fear and depression can be overcome with support.',
      keywords: ['anxiety', 'worry', 'fear', 'depression', 'nightmares'],
      description: 'The Nine of Swords represents anxiety, worry and fear. It signifies sleepless nights and overwhelming stress.',
    },
    reversed: {
      meaning: 'Releasing fear, recovery, moving on, inner peace, relief',
      keywords: ['releasing fear', 'recovery', 'moving on', 'inner peace', 'relief'],
      description: 'The Nine of Swords reversed suggests releasing fear, recovery, moving on, inner peace and relief.',
    },
  },
  {
    id: 'minor_arcana_swords_10',
    name: 'Ten of Swords',
    number: 10,
    type: 'minor',
    suit: 'swords',
    image: '/cards/minor/minor_arcana_swords_10.png',
    keywords: ['painful endings', 'deep wounds', 'betrayal', 'loss', 'crisis'],
    upright: {
      meaning: 'Face painful endings and deep wounds. Betrayal and loss lead to new beginnings.',
      keywords: ['painful endings', 'deep wounds', 'betrayal', 'loss', 'crisis'],
      description: 'The Ten of Swords represents painful endings, deep wounds and betrayal. It signifies the end of a difficult chapter and the beginning of healing.',
    },
    reversed: {
      meaning: 'Recovery, regeneration, resilience, picking up the pieces, moving on',
      keywords: ['recovery', 'regeneration', 'resilience', 'picking up the pieces', 'moving on'],
      description: 'The Ten of Swords reversed suggests recovery, regeneration, resilience, picking up the pieces and moving on.',
    },
  },
  {
    id: 'minor_arcana_swords_page',
    name: 'Page of Swords',
    number: 11,
    type: 'minor',
    suit: 'swords',
    court: 'page',
    image: '/cards/minor/minor_arcana_swords_page.png',
    keywords: ['new ideas', 'curiosity', 'thirst for knowledge', 'new ways of communicating', 'mental clarity'],
    upright: {
      meaning: 'Embrace new ideas and curiosity. Thirst for knowledge brings mental clarity.',
      keywords: ['new ideas', 'curiosity', 'thirst for knowledge', 'new ways of communicating', 'mental clarity'],
      description: 'The Page of Swords represents new ideas, curiosity and thirst for knowledge. He is the messenger who brings fresh perspectives.',
    },
    reversed: {
      meaning: 'Gossip, talking behind backs, mental overwhelm, communication issues, lack of focus',
      keywords: ['gossip', 'talking behind backs', 'mental overwhelm', 'communication issues', 'lack of focus'],
      description: 'The Page of Swords reversed suggests gossip, talking behind backs, mental overwhelm, communication issues and lack of focus.',
    },
  },
  {
    id: 'minor_arcana_swords_knight',
    name: 'Knight of Swords',
    number: 12,
    type: 'minor',
    suit: 'swords',
    court: 'knight',
    image: '/cards/minor/minor_arcana_swords_knight.png',
    keywords: ['ambitious', 'action-oriented', 'driven to succeed', 'fast-thinking', 'protective'],
    upright: {
      meaning: 'Channel your ambition into action. Fast-thinking and drive lead to success.',
      keywords: ['ambitious', 'action-oriented', 'driven to succeed', 'fast-thinking', 'protective'],
      description: 'The Knight of Swords represents ambition, action and drive. He is the warrior who charges forward with determination.',
    },
    reversed: {
      meaning: 'Scattered energy, lack of direction, impulsiveness, aggressive, rash decisions',
      keywords: ['scattered energy', 'lack of direction', 'impulsiveness', 'aggressive', 'rash decisions'],
      description: 'The Knight of Swords reversed suggests scattered energy, lack of direction, impulsiveness, aggressive and rash decisions.',
    },
  },
  {
    id: 'minor_arcana_swords_queen',
    name: 'Queen of Swords',
    number: 13,
    type: 'minor',
    suit: 'swords',
    court: 'queen',
    image: '/cards/minor/minor_arcana_swords_queen.png',
    keywords: ['independent', 'unbiased judgement', 'clear boundaries', 'direct communication', 'firm'],
    upright: {
      meaning: 'Maintain independence and unbiased judgement. Clear boundaries and direct communication serve you.',
      keywords: ['independent', 'unbiased judgement', 'clear boundaries', 'direct communication', 'firm'],
      description: 'The Queen of Swords represents independence, unbiased judgement and clear boundaries. She is the truth-teller who speaks with clarity and firmness.',
    },
    reversed: {
      meaning: 'Isolation, loneliness, bitterness, coldness, harsh judgement',
      keywords: ['isolation', 'loneliness', 'bitterness', 'coldness', 'harsh judgement'],
      description: 'The Queen of Swords reversed suggests isolation, loneliness, bitterness, coldness and harsh judgement.',
    },
  },
  {
    id: 'minor_arcana_swords_king',
    name: 'King of Swords',
    number: 14,
    type: 'minor',
    suit: 'swords',
    court: 'king',
    image: '/cards/minor/minor_arcana_swords_king.png',
    keywords: ['mental clarity', 'intellectual power', 'authority', 'truth', 'discipline'],
    upright: {
      meaning: 'Exercise mental clarity and intellectual power. Authority and truth guide your discipline.',
      keywords: ['mental clarity', 'intellectual power', 'authority', 'truth', 'discipline'],
      description: 'The King of Swords represents mental clarity, intellectual power and authority. He is the wise ruler who governs with truth and discipline.',
    },
    reversed: {
      meaning: 'Manipulative, abusive, controlling, harsh, ruthless',
      keywords: ['manipulative', 'abusive', 'controlling', 'harsh', 'ruthless'],
      description: 'The King of Swords reversed suggests manipulative, abusive, controlling, harsh and ruthless behavior.',
    },
  },

  // Minor Arcana - Pentacles (14 cards)
  {
    id: 'minor_arcana_pentacles_ace',
    name: 'Ace of Pentacles',
    number: 1,
    type: 'minor',
    suit: 'pentacles',
    image: '/cards/minor/minor_arcana_pentacles_ace.png',
    keywords: ['a new financial opportunity', 'manifestation', 'abundance', 'new venture', 'prosperity'],
    upright: {
      meaning: 'A new financial opportunity is coming. Manifest abundance and prosperity.',
      keywords: ['a new financial opportunity', 'manifestation', 'abundance', 'new venture', 'prosperity'],
      description: 'The Ace of Pentacles represents a new financial opportunity, manifestation and abundance. It signifies the start of a prosperous venture.',
    },
    reversed: {
      meaning: 'Missed opportunity, poor investment, financial loss, lack of abundance, scarcity mindset',
      keywords: ['missed opportunity', 'poor investment', 'financial loss', 'lack of abundance', 'scarcity mindset'],
      description: 'The Ace of Pentacles reversed suggests missed opportunity, poor investment, financial loss, lack of abundance and scarcity mindset.',
    },
  },
  {
    id: 'minor_arcana_pentacles_2',
    name: 'Two of Pentacles',
    number: 2,
    type: 'minor',
    suit: 'pentacles',
    image: '/cards/minor/minor_arcana_pentacles_2.png',
    keywords: ['multiple priorities', 'time management', 'prioritisation', 'adaptability', 'flexibility'],
    upright: {
      meaning: 'Manage multiple priorities with time management. Adaptability and flexibility are key.',
      keywords: ['multiple priorities', 'time management', 'prioritisation', 'adaptability', 'flexibility'],
      description: 'The Two of Pentacles represents multiple priorities, time management and adaptability. It signifies the need to balance competing demands.',
    },
    reversed: {
      meaning: 'Overwhelmed, disorganized, scattered energy, lack of balance, poor time management',
      keywords: ['overwhelmed', 'disorganized', 'scattered energy', 'lack of balance', 'poor time management'],
      description: 'The Two of Pentacles reversed suggests overwhelmed, disorganized, scattered energy, lack of balance and poor time management.',
    },
  },
  {
    id: 'minor_arcana_pentacles_3',
    name: 'Three of Pentacles',
    number: 3,
    type: 'minor',
    suit: 'pentacles',
    image: '/cards/minor/minor_arcana_pentacles_3.png',
    keywords: ['teamwork', 'collaboration', 'learning', 'implementation', 'building'],
    upright: {
      meaning: 'Collaborate with others through teamwork. Learning and implementation lead to building.',
      keywords: ['teamwork', 'collaboration', 'learning', 'implementation', 'building'],
      description: 'The Three of Pentacles represents teamwork, collaboration and learning. It signifies the importance of working together to achieve goals.',
    },
    reversed: {
      meaning: 'Lack of teamwork, poor collaboration, group conflict, low quality work, lack of skills',
      keywords: ['lack of teamwork', 'poor collaboration', 'group conflict', 'low quality work', 'lack of skills'],
      description: 'The Three of Pentacles reversed suggests lack of teamwork, poor collaboration, group conflict, low quality work and lack of skills.',
    },
  },
  {
    id: 'minor_arcana_pentacles_4',
    name: 'Four of Pentacles',
    number: 4,
    type: 'minor',
    suit: 'pentacles',
    image: '/cards/minor/minor_arcana_pentacles_4.png',
    keywords: ['saving money', 'security', 'conservatism', 'scarcity', 'control'],
    upright: {
      meaning: 'Save money and seek security. Conservatism and control provide stability.',
      keywords: ['saving money', 'security', 'conservatism', 'scarcity', 'control'],
      description: 'The Four of Pentacles represents saving money, security and conservatism. It signifies the desire to hold onto what you have.',
    },
    reversed: {
      meaning: 'Greed, generosity, spending, letting go, financial freedom',
      keywords: ['greed', 'generosity', 'spending', 'letting go', 'financial freedom'],
      description: 'The Four of Pentacles reversed suggests greed, generosity, spending, letting go and financial freedom.',
    },
  },
  {
    id: 'minor_arcana_pentacles_5',
    name: 'Five of Pentacles',
    number: 5,
    type: 'minor',
    suit: 'pentacles',
    image: '/cards/minor/minor_arcana_pentacles_5.png',
    keywords: ['financial loss', 'poverty', 'lack mindset', 'financial struggle', 'isolation'],
    upright: {
      meaning: 'Face financial loss and poverty. A lack mindset leads to financial struggle.',
      keywords: ['financial loss', 'poverty', 'lack mindset', 'financial struggle', 'isolation'],
      description: 'The Five of Pentacles represents financial loss, poverty and lack mindset. It signifies hardship and the feeling of being left out in the cold.',
    },
    reversed: {
      meaning: 'Financial recovery, finding help, spiritual wealth, reclaiming power, hope',
      keywords: ['financial recovery', 'finding help', 'spiritual wealth', 'reclaiming power', 'hope'],
      description: 'The Five of Pentacles reversed suggests financial recovery, finding help, spiritual wealth, reclaiming power and hope.',
    },
  },
  {
    id: 'minor_arcana_pentacles_6',
    name: 'Six of Pentacles',
    number: 6,
    type: 'minor',
    suit: 'pentacles',
    image: '/cards/minor/minor_arcana_pentacles_6.png',
    keywords: ['giving', 'receiving', 'sharing wealth', 'generosity', 'charity'],
    upright: {
      meaning: 'Practice giving and receiving. Share your wealth through generosity and charity.',
      keywords: ['giving', 'receiving', 'sharing wealth', 'generosity', 'charity'],
      description: 'The Six of Pentacles represents giving, receiving and sharing wealth. It signifies the flow of abundance through generosity.',
    },
    reversed: {
      meaning: 'Debt, unfairness, one-sided, stinginess, power imbalance',
      keywords: ['debt', 'unfairness', 'one-sided', 'stinginess', 'power imbalance'],
      description: 'The Six of Pentacles reversed suggests debt, unfairness, one-sided relationships, stinginess and power imbalance.',
    },
  },
  {
    id: 'minor_arcana_pentacles_7',
    name: 'Seven of Pentacles',
    number: 7,
    type: 'minor',
    suit: 'pentacles',
    image: '/cards/minor/minor_arcana_pentacles_7.png',
    keywords: ['long-term view', 'sustainable results', 'perseverance', 'investment', 'patience'],
    upright: {
      meaning: 'Take a long-term view for sustainable results. Perseverance and investment require patience.',
      keywords: ['long-term view', 'sustainable results', 'perseverance', 'investment', 'patience'],
      description: 'The Seven of Pentacles represents long-term view, sustainable results and perseverance. It signifies the need to be patient and wait for your efforts to bear fruit.',
    },
    reversed: {
      meaning: 'Impatience, lack of long-term vision, poor investment, giving up too soon, short-term focus',
      keywords: ['impatience', 'lack of long-term vision', 'poor investment', 'giving up too soon', 'short-term focus'],
      description: 'The Seven of Pentacles reversed suggests impatience, lack of long-term vision, poor investment, giving up too soon and short-term focus.',
    },
  },
  {
    id: 'minor_arcana_pentacles_8',
    name: 'Eight of Pentacles',
    number: 8,
    type: 'minor',
    suit: 'pentacles',
    image: '/cards/minor/minor_arcana_pentacles_8.png',
    keywords: ['apprenticeship', 'repetitive tasks', 'mastery', 'skill development', 'diligence'],
    upright: {
      meaning: 'Embrace apprenticeship and repetitive tasks. Mastery and skill development require diligence.',
      keywords: ['apprenticeship', 'repetitive tasks', 'mastery', 'skill development', 'diligence'],
      description: 'The Eight of Pentacles represents apprenticeship, repetitive tasks and mastery. It signifies the dedication to honing your craft.',
    },
    reversed: {
      meaning: 'Lack of passion, boredom, aimlessness, lack of focus, poor quality work',
      keywords: ['lack of passion', 'boredom', 'aimlessness', 'lack of focus', 'poor quality work'],
      description: 'The Eight of Pentacles reversed suggests lack of passion, boredom, aimlessness, lack of focus and poor quality work.',
    },
  },
  {
    id: 'minor_arcana_pentacles_9',
    name: 'Nine of Pentacles',
    number: 9,
    type: 'minor',
    suit: 'pentacles',
    image: '/cards/minor/minor_arcana_pentacles_9.png',
    keywords: ['abundance', 'luxury', 'self-sufficiency', 'financial independence', 'fulfillment'],
    upright: {
      meaning: 'Enjoy abundance and luxury. Self-sufficiency and financial independence bring fulfillment.',
      keywords: ['abundance', 'luxury', 'self-sufficiency', 'financial independence', 'fulfillment'],
      description: 'The Nine of Pentacles represents abundance, luxury and self-sufficiency. It signifies the rewards of hard work and financial independence.',
    },
    reversed: {
      meaning: 'Overspending, overindulgence, lack of discipline, financial insecurity, self-worth issues',
      keywords: ['overspending', 'overindulgence', 'lack of discipline', 'financial insecurity', 'self-worth issues'],
      description: 'The Nine of Pentacles reversed suggests overspending, overindulgence, lack of discipline, financial insecurity and self-worth issues.',
    },
  },
  {
    id: 'minor_arcana_pentacles_10',
    name: 'Ten of Pentacles',
    number: 10,
    type: 'minor',
    suit: 'pentacles',
    image: '/cards/minor/minor_arcana_pentacles_10.png',
    keywords: ['wealth', 'financial security', 'family', 'long-term success', 'contribution'],
    upright: {
      meaning: 'Achieve wealth and financial security. Family and long-term success bring fulfillment.',
      keywords: ['wealth', 'financial security', 'family', 'long-term success', 'contribution'],
      description: 'The Ten of Pentacles represents wealth, financial security and family. It signifies the culmination of long-term success and the legacy you leave behind.',
    },
    reversed: {
      meaning: 'Financial failure, loss of fortune, family conflict, scarcity, lack of stability',
      keywords: ['financial failure', 'loss of fortune', 'family conflict', 'scarcity', 'lack of stability'],
      description: 'The Ten of Pentacles reversed suggests financial failure, loss of fortune, family conflict, scarcity and lack of stability.',
    },
  },
  {
    id: 'minor_arcana_pentacles_page',
    name: 'Page of Pentacles',
    number: 11,
    type: 'minor',
    suit: 'pentacles',
    court: 'page',
    image: '/cards/minor/minor_arcana_pentacles_page.png',
    keywords: ['manifestation', 'financial opportunity', 'skill building', 'diligence', 'focus'],
    upright: {
      meaning: 'Manifest your desires and seize financial opportunities. Skill building requires diligence and focus.',
      keywords: ['manifestation', 'financial opportunity', 'skill building', 'diligence', 'focus'],
      description: 'The Page of Pentacles represents manifestation, financial opportunity and skill building. He is the diligent student who focuses on practical matters.',
    },
    reversed: {
      meaning: 'Lack of focus, procrastination, distraction, lack of commitment, poor planning',
      keywords: ['lack of focus', 'procrastination', 'distraction', 'lack of commitment', 'poor planning'],
      description: 'The Page of Pentacles reversed suggests lack of focus, procrastination, distraction, lack of commitment and poor planning.',
    },
  },
  {
    id: 'minor_arcana_pentacles_knight',
    name: 'Knight of Pentacles',
    number: 12,
    type: 'minor',
    suit: 'pentacles',
    court: 'knight',
    image: '/cards/minor/minor_arcana_pentacles_knight.png',
    keywords: ['hard work', 'productivity', 'routine', 'conservatism', 'methodical'],
    upright: {
      meaning: 'Work hard and be productive. Routine and conservatism lead to methodical success.',
      keywords: ['hard work', 'productivity', 'routine', 'conservatism', 'methodical'],
      description: 'The Knight of Pentacles represents hard work, productivity and routine. He is the methodical worker who takes a steady approach to achieving goals.',
    },
    reversed: {
      meaning: 'Stuck, stubborn, bored, restless, lack of progress',
      keywords: ['stuck', 'stubborn', 'bored', 'restless', 'lack of progress'],
      description: 'The Knight of Pentacles reversed suggests being stuck, stubborn, bored, restless and lack of progress.',
    },
  },
  {
    id: 'minor_arcana_pentacles_queen',
    name: 'Queen of Pentacles',
    number: 13,
    type: 'minor',
    suit: 'pentacles',
    court: 'queen',
    image: '/cards/minor/minor_arcana_pentacles_queen.png',
    keywords: ['nurturing', 'practical', 'providing financially', 'a working parent', 'abundance'],
    upright: {
      meaning: 'Nurture others with practical care. Providing financially brings abundance and security.',
      keywords: ['nurturing', 'practical', 'providing financially', 'a working parent', 'abundance'],
      description: 'The Queen of Pentacles represents nurturing, practical care and financial provision. She is the abundant provider who creates a warm and comfortable home.',
    },
    reversed: {
      meaning: 'Selfish, jealous, insecure, overprotective, financially dependent',
      keywords: ['selfish', 'jealous', 'insecure', 'overprotective', 'financially dependent'],
      description: 'The Queen of Pentacles reversed suggests selfishness, jealousy, insecurity, overprotectiveness and financial dependence.',
    },
  },
  {
    id: 'minor_arcana_pentacles_king',
    name: 'King of Pentacles',
    number: 14,
    type: 'minor',
    suit: 'pentacles',
    court: 'king',
    image: '/cards/minor/minor_arcana_pentacles_king.png',
    keywords: ['wealth', 'business', 'leadership', 'security', 'discipline'],
    upright: {
      meaning: 'Build wealth and business through leadership. Security and discipline create prosperity.',
      keywords: ['wealth', 'business', 'leadership', 'security', 'discipline'],
      description: 'The King of Pentacles represents wealth, business and leadership. He is the successful entrepreneur who has mastered the material world.',
    },
    reversed: {
      meaning: 'Greed, corruption, materialism, controlling, stubborn',
      keywords: ['greed', 'corruption', 'materialism', 'controlling', 'stubborn'],
      description: 'The King of Pentacles reversed suggests greed, corruption, materialism, controlling and stubborn behavior.',
    },
  },
];